CREATE TABLE IF NOT EXISTS 't_channel' (
  'id',
  'express_id',
  'channel_code',
  'product_category',
  'description',
  'cost_1',
  'cost_2',
  'cost_our_1',
  'cost_our_2',
  'is_in_use',
  'log',
  'created_at',
  'updated_at',
) ENGINE=
