CREATE TABLE IF NOT EXISTS 't_forecast_detail' (
  'id',
  'user_type',
  'user_id',
  'express_id',
  'seq_num',
  'trade_id',
  'sku_id',
  'product_id',
  'title',
  'quantity',
  'price',
  'forecast_type',
  'channel_id',
  'insurance_amount',
  'cost_insurance',
  'cost_insurance_out',
  'remark_user',
  'date_update',
  'status',
  'created_at',
  'updated_at',
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COMMENT='预报详情表（商家/海淘客提交发货/入库指令表）' AUTO_INCREMENT=6 ;

