CREATE TABLE IF NOT EXISTS 't_ship_history' (
  'id',
  'trade_id',
  'user_type',
  'user_id',
  'express_id',
  'tracking_no',
  'recipient',
  'status',
  'weight',
  'channel_id',
  'cost_shipping',
  'cost_shipping_our',
  'buy_insurance',
  'insurance_amount',
  'cost_insurance',
  'cost_insurance_our',
  'cost_total',
  'cost_total_our',
  'remark_user',
  'remark_express',
  'log',
  'created_at',
  'updated_at',
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='国际快递发货记录' AUTO_INCREMENT=1 ;

