CREATE TABLE IF NOT EXISTS 't_trade_product' (
  'id',
  'trade_id',
  'sku_id',
  'product_id',
  'quantity',
  'quantity_shipped',
  'item_id',
  'sku_origin',
  'title',
  'img_mini',
  'img',
  'date_upload',
  'date_receive',
  'date_complete',
  'price',
  'pay_type',
  'status',
  'date_status_update',
  'remark_seller',
  'log',
  'created_at',
  'updated_at',
  KEY 'radio_status',
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3137 ;

